### ISSUE TITLE
Crash on Apple Silicon trying to use Accelerate

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/libblastrampoline#102]
I believe LBT should be able to detect the LP64 interface and forward those symbols.

```
julia> using LinearAlgebra

julia> using Libdl; libacc = dlopen("/System/Library/Frameworks/Accelerate.framework/Accelerate")
Ptr{Nothing} @0x00000003e1f58480

julia> BLAS.lbt_forward(libacc; clear=true, suffix_hint="")

signal (11): Segmentation fault: 11
in expression starting at REPL[3]:1
_ZN5dyld39MachOFile8trieWalkER11DiagnosticsPKhS4_PKc at /usr/lib/dyld (unknown line)
Allocations: 785624 (Pool: 785337; Big: 287); GC: 1
```

**Comment by staticfloat** [comment]
This is because `lbt_forward` [takes in a path as a string](https://github.com/JuliaLang/julia/blob/3fe69f4f4327dd4f9d39a8d8b5ff2d959113d680/stdlib/LinearAlgebra/src/lbt.jl#L210-L214), not an already-opened handle.  Unfortunately, it appears that you can pass a `Ptr{Cvoid}` in as a `Cstring` without raising any alarms, which I did not know about.  Perhaps we should change `lbt_forward` to take in `path` as an `::AbstractString` to prevent this in the future.

**Comment by ViralBShah** [comment]
Sorry for the noise on this.
