### ISSUE TITLE
List BLAS libraries known to work with libblastrampoline

### ISSUE THREAD

**Issue by giordano** [JuliaLinearAlgebra/libblastrampoline#63]
It'd be good to list somewhere (README?) the BLAS libraries known to work with libblastrampoline.  I'll start collecting them in this issue:

* OpenBLAS (what's used directly in Julia)
* MKL via [`MKL.jl`](https://github.com/JuliaLinearAlgebra/MKL.jl)
* blis (after https://github.com/JuliaPackaging/Yggdrasil/pull/4463)
* Fujitsu BLAS via [`FujitsuBLAS.jl`](https://github.com/giordano/FujitsuBLAS.jl)

Do you know more?

**Comment by ViralBShah** [comment]
Accelerate had been tested in the early days and probably works.

Note that you have to have a table for BLAS and LAPACK for each case (only OpenBLAS and MKL). And we need to address https://github.com/JuliaPackaging/Yggdrasil/issues/2657 for the solution to be reasonably complete. Just forwarding BLAS is not useful at all.

And after that is all in shape, we need to link all the libraries in Yggdrasil to LBT instead of openblas/MKL/etc.

**Comment by carstenbauer** [comment]
Does [FlexiBLAS](https://www.mpi-magdeburg.mpg.de/projects/flexiblas) work? If not, would be great to support it because it is shipped in some standard toolchains on HPC clusters (for easybuild in all modern foss toolchains, see e.g. https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/f/foss/foss-2021b.eb).
